codecov:
  require_ci_to_pass: yes

coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: no           
    patch:
      default:
        enabled: no
  